package com.defang.drools.rules
import com.huahuayu.drools.model.Order
import com.huahuayu.drools.model.Result

rule "ordinary customer, 10% off"
when
$order:Order($order.getCustomer().getType() == "1");
$result:Result();
then
$result.setDiscount(0.9f);
$result.setFinalPrice($order.getProduct().getPrice() * 0.9f);
 end

rule "vip, 20% off"
when
$order:Order($order.getCustomer().getType() == "2");
$result:Result();
then
$result.setDiscount(0.8f);
$result.setFinalPrice($order.getProduct().getPrice() * 0.8f);
 end

rule "advanced vip, 30% off"
when
$order:Order($order.getCustomer().getType() == "3");
$result:Result();
then
$result.setDiscount(0.7f);
$result.setFinalPrice($order.getProduct().getPrice() * 0.7f);
 end
