package com.defang.drools.rules
import com.defang.drools.dto.Car
import com.defang.drools.dto.Person

rule "大于等于60"
when
$car:Car(person.age>=60)
then
$car.setFinalPrice($car.getPrice()*0.5f);
System.out.println("大于等于60");
 end

rule "大于20，小于60"
when
$car:Car(person.age>=20 && person.age<60)
then
$car.setFinalPrice($car.getPrice()*0.6f);
System.out.println("大于等于20小于60");
 end

rule "小于20"
when
$car:Car(person.age<20)
then
$car.setFinalPrice($car.getPrice()*0.8f);
System.out.println("小于60");
 end
