package com.defang.drools.rules
import com.defang.drools.model.Order
import com.defang.drools.model.Result

rule "ordinary customer, 10% off"
when
$order:Order($order.getCustomer().getType() == "1");
then
$result:Result($result.setDiscount(0.9f));
$result:Result($resuylt.setFinalPrice($order.getProduct().getPrice() * 0.9f);
 end

rule "vip, 20% off"
when
$order:Order($order.getCustomer().getType() == "2");
then
$result:Result($result.setDiscount(0.8f));
$result:Result($resuylt.setFinalPrice($order.getProduct().getPrice() * 0.8f);
 end

rule "advanced vip, 30% off"
when
$order:Order($order.getCustomer().getType() == "3");
then
$result:Result($result.setDiscount(0.7f));
$result:Result($resuylt.setFinalPrice($order.getProduct().getPrice() * 0.7f);
 end
